### ISSUE TITLE
Using cURL ?

### ISSUE THREAD

**Issue by anteksiler** [empatogen/woocommerce-xrp#1]
I was wondering why you have not used wp_remote_post or wp_safe_remote_post

**Comment by empatogen** [comment]
Oh, I had no idea those actually existed.. :flushed:

**Comment by anteksiler** [comment]
Looks like you can remove the additional curl library :)

**Comment by empatogen** [comment]
It didn't take long before v1.0.1 got released. No more cURL dependency! :sunglasses:
