### ISSUE TITLE
Are you considering implementing a singleton pattern?

### ISSUE THREAD

**Issue by tarotaro080808** [empatogen/woocommerce-xrp#12]
Many plugins use a singleton pattern.
I recommend the implementation of the singleton pattern so as not to pollute the world.

I made a sample code.
Please see if it is good. (Insufficient operation check)

https://github.com/tarotaro080808/woocommerce-xrp/tree/Singleton-pattern

**Comment by empatogen** [comment]
Looks indeed interesting. I'm not a big fan of Wordpress coding style at all and this is my first plugin actually. I'll read up on singleton patterns and see what I can do. :+1:

**Comment by tarotaro080808** [comment]
Thank you!
Is this the first plugin you made? This is amazing. :)

I think it is good to prove that there is only one instance of the main class.

**Comment by empatogen** [comment]
Fixed by 4045846921b55396fe2d0c80ec5e70e66ca17154

**Comment by tarotaro080808** [comment]
This is fantastic!
It looks like there is no problem.
