### ISSUE TITLE
Conflict with Gourl.io woocommerce plugin

### ISSUE THREAD

**Issue by rpersonal2** [empatogen/woocommerce-xrp#4]
Love this plugin but if using the Gourl.io plugin for Bitcoin, Litcoin, etc., there is an issue on the payment page.

Selecting XRP payment options works as expected however selected Bitcoin (gourl.io) option shows both the bitcoin payment and xrp payment on the same page.  I was expecting to only see the bitcoin option.
![Payment Options](https://user-images.githubusercontent.com/47085580/54478907-b8c3f680-47d4-11e9-9c76-b4aef0c18d96.PNG)
![Payment Page when Bitcoin Gourl selected](https://user-images.githubusercontent.com/47085580/54478908-b8c3f680-47d4-11e9-8a1c-b72de582d793.PNG)
![Payment Page when XRP selected](https://user-images.githubusercontent.com/47085580/54478909-b8c3f680-47d4-11e9-92d4-76d3115ab6d5.PNG)

**Comment by empatogen** [comment]
[This commit](https://github.com/empatogen/woocommerce-xrp/commit/963dda8d068e65afe7582c7438557bc329ae2503) fixes this. Thanks for reporting this!
