### ISSUE TITLE
Error in random_int on 32bit machines

### ISSUE THREAD

**Issue by jetwes** [empatogen/woocommerce-xrp#8]
If wordpress is hosted on a 32bit machine (could be with machines running shared hosting) you'll get an error on checkout: "CRITICAL Uncaught TypeError: random_int() expects parameter 2 to be integer, float given in". That's because int larger than 2147483647 are treaten as float on 32bit machines...

**Comment by empatogen** [comment]
Fixed by a12ad7577a0ff02a74d8aa841a65da6b5941daea :+1:
